### ISSUE TITLE
Implement `Process` to match the JavaScript API

### ISSUE THREAD

**Issue by Xoffio** [frida/frida-rust#187]
We can use the JavaScript API docs as a goal -> https://frida.re/docs/javascript-api/#process

- [x] `Process.id` done in #182
- [ ] `Process.arch`
- [x] `Process.platform` done in #182
- [ ] `Process.pageSize`
- [ ] `Process.pointerSize`
- [x] `Process.codeSigningPolicy` done in #182
- [x] `Process.mainModule` done in #182
- [ ] `Process.getCurrentDir()`
- [ ] `Process.getHomeDir()`
- [ ] `Process.getTmpDir()`
- [ ] `Process.isDebuggerAttached()`
- [ ] `Process.getCurrentThreadId()`
- [ ] `Process.enumerateThreads()`
- [ ] `Process.findModuleByAddress(address), Process.getModuleByAddress(address), Process.findModuleByName(name), Process.getModuleByName(name)`
- [ ] `Process.enumerateModules()`
- [ ] `Process.findRangeByAddress(address), getRangeByAddress(address)`
- [x] `Process.enumerateRanges(protection|specifier)` done in #182
- [ ] `Process.enumerateMallocRanges()`
- [ ] `Process.setExceptionHandler(callback)`

We can keep this issue open to track the progress and close it once its done :)
